#ifndef QNDIMANAGERCORE_GLOBAL_H
#define QNDIMANAGERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDIMANAGERCORE_EXPORTS)
#  define QNDIMANAGERCORE_EXPORT Q_DECL_EXPORT
#else
#  define QNDIMANAGERCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDIMANAGERCORE_GLOBAL_H 