#ifndef QNDIMANAGERQUICK_GLOBAL_H
#define QNDIMANAGERQUICK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDIMANAGERQUICK_EXPORTS)
#  define QNDIMANAGERQUICK_EXPORT Q_DECL_EXPORT
#else
#  define QNDIMANAGERQUICK_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDIMANAGERQUICK_GLOBAL_H 