#ifndef QNDISOURCEQUICK_GLOBAL_H
#define QNDISOURCEQUICK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDISOURCEQUICK_EXPORTS)
#  define QNDISOURCEQUICK_EXPORT Q_DECL_EXPORT
#else
#  define QNDISOURCEQUICK_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDISOURCEQUICK_GLOBAL_H 