#ifndef QNDIKITMANAGER_GLOBAL_H
#define QNDIKITMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDIKIT_MANAGER_CORE_LIBRARY)
#  define QNDIKITMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define QNDIKITMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDIKITMANAGER_GLOBAL_H 