#ifndef QNDIMANAGERWIDGETS_GLOBAL_H
#define QNDIMANAGERWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDIMANAGERWIDGETS_EXPORTS)
#  define QNDIMANAGERWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QNDIMANAGERWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDIMANAGERWIDGETS_GLOBAL_H 