#ifndef QNDIKITSOURCE_GLOBAL_H
#define QNDIKITSOURCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDIKIT_SOURCE_CORE_LIBRARY)
#  define QNDIKITSOURCE_EXPORT Q_DECL_EXPORT
#else
#  define QNDIKITSOURCE_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDIKITSOURCE_GLOBAL_H 