#ifndef QNDISOURCEWIDGETS_GLOBAL_H
#define QNDISOURCEWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNDISOURCEWIDGETS_EXPORTS)
#  define QNDISOURCEWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QNDISOURCEWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QNDISOURCEWIDGETS_GLOBAL_H 